import puppeteer from 'puppeteer';
import { db } from '../prisma/db';
import { r2 } from '../lib/r2';
import { HttpError } from '../lib/http-error';

class CatalogService {
  async generateArtisanPdf(artisanId: number): Promise<Buffer> {
    const artisan = await db.orm.public.Artisan
      .where({ id: artisanId })
      .include('user', (u) => u)
      .all()
      .first();
    if (!artisan) throw new HttpError(404, 'Artisan not found.');

    const products = await db.orm.public.Product.where({
      artisanId,
      status: 'published',
    })
      .include('catalogue', (c) => c)
      .include('pricing', (p) => p)
      .include('images', (img) => img)
      .all();

    // Pre-fetch image URLs and convert to base64 data URIs for inline embedding
    const productCards = await Promise.all(
      products.map(async (product: any) => {
        const imgKey = product.images?.[0]?.outputSquareKey;
        let imageHtml = '<div style="width:100%;height:200px;background:#f0f0f0;border-radius:8px;display:flex;align-items:center;justify-content:center;color:#999;">No Image</div>';
        if (imgKey) {
          try {
            const url = await r2.getAccessUrl(imgKey, 3600);
            const res = await fetch(url);
            if (res.ok) {
              const buf = Buffer.from(await res.arrayBuffer());
              const b64 = buf.toString('base64');
              const mime = imgKey.endsWith('.png') ? 'image/png' : 'image/jpeg';
              imageHtml = `<img src="data:${mime};base64,${b64}" style="width:100%;height:200px;object-fit:cover;border-radius:8px;" />`;
            }
          } catch { /* fall through to placeholder */ }
        }

        const title = product.catalogue?.titleEn || product.name;
        const desc = product.catalogue?.descriptionEn || product.description || '';
        const price = product.pricing?.recommendedPrice ?? product.price;

        return `
          <div class="card">
            ${imageHtml}
            <div class="card-body">
              <h3>${title}</h3>
              <p class="desc">${desc.slice(0, 120)}${desc.length > 120 ? '…' : ''}</p>
              <div class="meta">
                <span class="price">₹${price != null ? Number(price).toLocaleString('en-IN') : '—'}</span>
                <span class="qty">Qty: ${product.quantity}</span>
              </div>
              <div class="tags">
                ${product.material ? `<span class="tag">${product.material}</span>` : ''}
                ${product.category ? `<span class="tag">${product.category}</span>` : ''}
              </div>
            </div>
          </div>`;
      }),
    );

    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; color: #222; }
    .header { text-align: center; margin-bottom: 32px; border-bottom: 2px solid #e53935; padding-bottom: 16px; }
    .header h1 { font-size: 26px; color: #e53935; }
    .header .subtitle { font-size: 14px; color: #666; margin-top: 4px; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
    .card { border: 1px solid #ddd; border-radius: 10px; overflow: hidden; break-inside: avoid; }
    .card-body { padding: 12px; }
    .card-body h3 { font-size: 15px; margin-bottom: 4px; }
    .desc { font-size: 12px; color: #555; line-height: 1.4; margin-bottom: 6px; }
    .meta { display: flex; justify-content: space-between; font-size: 13px; margin-bottom: 6px; }
    .price { font-weight: 700; color: #e53935; }
    .qty { color: #888; }
    .tags { display: flex; gap: 6px; flex-wrap: wrap; }
    .tag { background: #f5f5f5; border: 1px solid #ddd; border-radius: 4px; padding: 2px 8px; font-size: 11px; }
    .footer { text-align: center; margin-top: 32px; font-size: 11px; color: #999; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${artisan.storeName || artisan.user?.name || 'Artisan'}</h1>
    <div class="subtitle">${artisan.craftType ?? ''} · ${artisan.district ?? ''}, ${artisan.state ?? ''} · ShilpSetu Catalog</div>
  </div>
  <div class="grid">
    ${productCards.join('\n')}
  </div>
  <div class="footer">
    Generated by ShilpSetu · ${new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}
  </div>
</body>
</html>`;

    const browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox'],
    });
    try {
      const page = await browser.newPage();
      await page.setContent(html);
      const pdfBuffer = await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: { top: '0', bottom: '0', left: '0', right: '0' },
      });
      return Buffer.from(pdfBuffer);
    } finally {
      await browser.close();
    }
  }
}

export const catalogService = new CatalogService();
